#!/bin/sh

#set -e
echo "Initial preparation...this can take awhile, so sit tight..."

aclocal

# We don't need libtool, but it creates config.sub & config.guess - <sigh>
libtoolize --automake --copy --force

# Create config.h
autoheader

# Neither do we need automake, but it provides "missing", "install-sh" and "mkinstalldirs"
automake --foreign --add-missing --copy

#Create configure script
autoconf

echo -n "Copying Makefiles"
cp tools/Makefile tools/disasm
echo -n "."
#cp tools/Makefile tools/fold
#echo -n "."
#cp tools/Makefile tools/suc
#echo -n "."
cp tools/Makefile misc
echo -n "."
cp tools/Makefile convert
echo -n "."
cp tools/Makefile convert/u8
echo -n "."
cp tools/Makefile filesys
echo -n "."

echo ""
echo "You are now ready to run ./configure ..."
